### ISSUE TITLE
Add more patterns.

### ISSUE THREAD

**Issue by harshhhdev** [YilianSource/party-js#4]
Add more patterns, such as random direction, or confetti from the sides, etc.

A demo of what I mean can be found [here]

[here]: https://www.kirilv.com/canvas-confetti/

**Comment by YilianSource** [comment]
Thanks for the suggestion, I'll definitely implement this!

The implementation will most likely end up being via the `options` object, rather than through a seperate methods. An option for the spread of the cone is already in place (`angleSpread`), but I admit that my current implementation is flawed, especially since it only allows a single direction to spread around.

The following options will be implemented, replacing their current flawed versions:
- initialVelocity
- initialVelocityVariation
- angle
- spread

**Comment by YilianSource** [comment]
Randomization here is linked to #6 now.
