### ISSUE TITLE
Is there an easy way to use this library with react?

### ISSUE THREAD

**Issue by BrunoSette** [yiliansource/party-js#40]

**Comment by yiliansource** [comment]
Can you give an example of what you want to do? In general I believe this should be possible fairly easily, although you might need to use the package-managed version rather than the browser-bundled one to ensure that the JSX is properly transpiled.

The only difficulty might be to get the reference to the HTMLElement you want to emit the particles from, however it should be possible via the `ref` attribute and usage of the `useRef(..)` method.

**Comment by yiliansource** [comment]
@BrunoSette As you can see in another issue (#48), it's fairly straightforward to use the library with React. Here's a short example:

```ts
import * as party from "party-js";

export default function App() {
  return (
    <div className="App">
      <h1 onClick={(e) => party.confetti(e.target)}>Party!</h1>
    </div>
  );
}
```

**Comment by BrunoSette** [comment]
I got it, thank you!
